import Head from "next/head";
import styles from "../styles/Home.module.css";
import Footer from "../components/Footer";
import MainArticle from "../components/MainArticle";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>State &amp; Props</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <MainArticle title="State &amp; Props" />
      </main>

      <Footer />
    </div>
  );
}
