import Head from "next/head";
import styles from "../styles/Home.module.css";
import Footer from "../components/Footer";
import MainArticle from "../components/MainArticle";
import Counter from "../components/Counter";
import "react-responsive-carousel/lib/styles/carousel.min.css";
import { Carousel } from "react-responsive-carousel";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>State &amp; Props</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Carousel>
        <div>
          <MainArticle title="League Champion Selection" />
        </div>
        <div>
          <Counter title="Counter" />
        </div>
      </Carousel>
      <Footer />
    </div>
  );
}
